// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package cart

//go:generate minimock -i shop/internal/cart.RepositoryInterface -o repository_mock_test.go -n RepositoryMock -p cart

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// RepositoryMock implements RepositoryInterface
type RepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcadd          func(userID int64, item Item)
	funcaddOrigin    string
	inspectFuncadd   func(userID int64, item Item)
	afteraddCounter  uint64
	beforeaddCounter uint64
	addMock          mRepositoryMockadd

	funcclear          func(userID int64)
	funcclearOrigin    string
	inspectFuncclear   func(userID int64)
	afterclearCounter  uint64
	beforeclearCounter uint64
	clearMock          mRepositoryMockclear

	funcget          func(userID int64) (m1 map[int64]Item)
	funcgetOrigin    string
	inspectFuncget   func(userID int64)
	aftergetCounter  uint64
	beforegetCounter uint64
	getMock          mRepositoryMockget

	funcremove          func(userID int64, sku int64)
	funcremoveOrigin    string
	inspectFuncremove   func(userID int64, sku int64)
	afterremoveCounter  uint64
	beforeremoveCounter uint64
	removeMock          mRepositoryMockremove
}

// NewRepositoryMock returns a mock for RepositoryInterface
func NewRepositoryMock(t minimock.Tester) *RepositoryMock {
	m := &RepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.addMock = mRepositoryMockadd{mock: m}
	m.addMock.callArgs = []*RepositoryMockaddParams{}

	m.clearMock = mRepositoryMockclear{mock: m}
	m.clearMock.callArgs = []*RepositoryMockclearParams{}

	m.getMock = mRepositoryMockget{mock: m}
	m.getMock.callArgs = []*RepositoryMockgetParams{}

	m.removeMock = mRepositoryMockremove{mock: m}
	m.removeMock.callArgs = []*RepositoryMockremoveParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mRepositoryMockadd struct {
	optional           bool
	mock               *RepositoryMock
	defaultExpectation *RepositoryMockaddExpectation
	expectations       []*RepositoryMockaddExpectation

	callArgs []*RepositoryMockaddParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RepositoryMockaddExpectation specifies expectation struct of the RepositoryInterface.add
type RepositoryMockaddExpectation struct {
	mock               *RepositoryMock
	params             *RepositoryMockaddParams
	paramPtrs          *RepositoryMockaddParamPtrs
	expectationOrigins RepositoryMockaddExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// RepositoryMockaddParams contains parameters of the RepositoryInterface.add
type RepositoryMockaddParams struct {
	userID int64
	item   Item
}

// RepositoryMockaddParamPtrs contains pointers to parameters of the RepositoryInterface.add
type RepositoryMockaddParamPtrs struct {
	userID *int64
	item   *Item
}

// RepositoryMockaddOrigins contains origins of expectations of the RepositoryInterface.add
type RepositoryMockaddExpectationOrigins struct {
	origin       string
	originUserID string
	originItem   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmadd *mRepositoryMockadd) Optional() *mRepositoryMockadd {
	mmadd.optional = true
	return mmadd
}

// Expect sets up expected params for RepositoryInterface.add
func (mmadd *mRepositoryMockadd) Expect(userID int64, item Item) *mRepositoryMockadd {
	if mmadd.mock.funcadd != nil {
		mmadd.mock.t.Fatalf("RepositoryMock.add mock is already set by Set")
	}

	if mmadd.defaultExpectation == nil {
		mmadd.defaultExpectation = &RepositoryMockaddExpectation{}
	}

	if mmadd.defaultExpectation.paramPtrs != nil {
		mmadd.mock.t.Fatalf("RepositoryMock.add mock is already set by ExpectParams functions")
	}

	mmadd.defaultExpectation.params = &RepositoryMockaddParams{userID, item}
	mmadd.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmadd.expectations {
		if minimock.Equal(e.params, mmadd.defaultExpectation.params) {
			mmadd.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmadd.defaultExpectation.params)
		}
	}

	return mmadd
}

// ExpectUserIDParam1 sets up expected param userID for RepositoryInterface.add
func (mmadd *mRepositoryMockadd) ExpectUserIDParam1(userID int64) *mRepositoryMockadd {
	if mmadd.mock.funcadd != nil {
		mmadd.mock.t.Fatalf("RepositoryMock.add mock is already set by Set")
	}

	if mmadd.defaultExpectation == nil {
		mmadd.defaultExpectation = &RepositoryMockaddExpectation{}
	}

	if mmadd.defaultExpectation.params != nil {
		mmadd.mock.t.Fatalf("RepositoryMock.add mock is already set by Expect")
	}

	if mmadd.defaultExpectation.paramPtrs == nil {
		mmadd.defaultExpectation.paramPtrs = &RepositoryMockaddParamPtrs{}
	}
	mmadd.defaultExpectation.paramPtrs.userID = &userID
	mmadd.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmadd
}

// ExpectItemParam2 sets up expected param item for RepositoryInterface.add
func (mmadd *mRepositoryMockadd) ExpectItemParam2(item Item) *mRepositoryMockadd {
	if mmadd.mock.funcadd != nil {
		mmadd.mock.t.Fatalf("RepositoryMock.add mock is already set by Set")
	}

	if mmadd.defaultExpectation == nil {
		mmadd.defaultExpectation = &RepositoryMockaddExpectation{}
	}

	if mmadd.defaultExpectation.params != nil {
		mmadd.mock.t.Fatalf("RepositoryMock.add mock is already set by Expect")
	}

	if mmadd.defaultExpectation.paramPtrs == nil {
		mmadd.defaultExpectation.paramPtrs = &RepositoryMockaddParamPtrs{}
	}
	mmadd.defaultExpectation.paramPtrs.item = &item
	mmadd.defaultExpectation.expectationOrigins.originItem = minimock.CallerInfo(1)

	return mmadd
}

// Inspect accepts an inspector function that has same arguments as the RepositoryInterface.add
func (mmadd *mRepositoryMockadd) Inspect(f func(userID int64, item Item)) *mRepositoryMockadd {
	if mmadd.mock.inspectFuncadd != nil {
		mmadd.mock.t.Fatalf("Inspect function is already set for RepositoryMock.add")
	}

	mmadd.mock.inspectFuncadd = f

	return mmadd
}

// Return sets up results that will be returned by RepositoryInterface.add
func (mmadd *mRepositoryMockadd) Return() *RepositoryMock {
	if mmadd.mock.funcadd != nil {
		mmadd.mock.t.Fatalf("RepositoryMock.add mock is already set by Set")
	}

	if mmadd.defaultExpectation == nil {
		mmadd.defaultExpectation = &RepositoryMockaddExpectation{mock: mmadd.mock}
	}

	mmadd.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmadd.mock
}

// Set uses given function f to mock the RepositoryInterface.add method
func (mmadd *mRepositoryMockadd) Set(f func(userID int64, item Item)) *RepositoryMock {
	if mmadd.defaultExpectation != nil {
		mmadd.mock.t.Fatalf("Default expectation is already set for the RepositoryInterface.add method")
	}

	if len(mmadd.expectations) > 0 {
		mmadd.mock.t.Fatalf("Some expectations are already set for the RepositoryInterface.add method")
	}

	mmadd.mock.funcadd = f
	mmadd.mock.funcaddOrigin = minimock.CallerInfo(1)
	return mmadd.mock
}

// When sets expectation for the RepositoryInterface.add which will trigger the result defined by the following
// Then helper
func (mmadd *mRepositoryMockadd) When(userID int64, item Item) *RepositoryMockaddExpectation {
	if mmadd.mock.funcadd != nil {
		mmadd.mock.t.Fatalf("RepositoryMock.add mock is already set by Set")
	}

	expectation := &RepositoryMockaddExpectation{
		mock:               mmadd.mock,
		params:             &RepositoryMockaddParams{userID, item},
		expectationOrigins: RepositoryMockaddExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmadd.expectations = append(mmadd.expectations, expectation)
	return expectation
}

// Then sets up RepositoryInterface.add return parameters for the expectation previously defined by the When method

func (e *RepositoryMockaddExpectation) Then() *RepositoryMock {
	return e.mock
}

// Times sets number of times RepositoryInterface.add should be invoked
func (mmadd *mRepositoryMockadd) Times(n uint64) *mRepositoryMockadd {
	if n == 0 {
		mmadd.mock.t.Fatalf("Times of RepositoryMock.add mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmadd.expectedInvocations, n)
	mmadd.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmadd
}

func (mmadd *mRepositoryMockadd) invocationsDone() bool {
	if len(mmadd.expectations) == 0 && mmadd.defaultExpectation == nil && mmadd.mock.funcadd == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmadd.mock.afteraddCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmadd.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// add implements RepositoryInterface
func (mmadd *RepositoryMock) add(userID int64, item Item) {
	mm_atomic.AddUint64(&mmadd.beforeaddCounter, 1)
	defer mm_atomic.AddUint64(&mmadd.afteraddCounter, 1)

	mmadd.t.Helper()

	if mmadd.inspectFuncadd != nil {
		mmadd.inspectFuncadd(userID, item)
	}

	mm_params := RepositoryMockaddParams{userID, item}

	// Record call args
	mmadd.addMock.mutex.Lock()
	mmadd.addMock.callArgs = append(mmadd.addMock.callArgs, &mm_params)
	mmadd.addMock.mutex.Unlock()

	for _, e := range mmadd.addMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmadd.addMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmadd.addMock.defaultExpectation.Counter, 1)
		mm_want := mmadd.addMock.defaultExpectation.params
		mm_want_ptrs := mmadd.addMock.defaultExpectation.paramPtrs

		mm_got := RepositoryMockaddParams{userID, item}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmadd.t.Errorf("RepositoryMock.add got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmadd.addMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.item != nil && !minimock.Equal(*mm_want_ptrs.item, mm_got.item) {
				mmadd.t.Errorf("RepositoryMock.add got unexpected parameter item, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmadd.addMock.defaultExpectation.expectationOrigins.originItem, *mm_want_ptrs.item, mm_got.item, minimock.Diff(*mm_want_ptrs.item, mm_got.item))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmadd.t.Errorf("RepositoryMock.add got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmadd.addMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmadd.funcadd != nil {
		mmadd.funcadd(userID, item)
		return
	}
	mmadd.t.Fatalf("Unexpected call to RepositoryMock.add. %v %v", userID, item)

}

// addAfterCounter returns a count of finished RepositoryMock.add invocations
func (mmadd *RepositoryMock) addAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmadd.afteraddCounter)
}

// addBeforeCounter returns a count of RepositoryMock.add invocations
func (mmadd *RepositoryMock) addBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmadd.beforeaddCounter)
}

// Calls returns a list of arguments used in each call to RepositoryMock.add.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmadd *mRepositoryMockadd) Calls() []*RepositoryMockaddParams {
	mmadd.mutex.RLock()

	argCopy := make([]*RepositoryMockaddParams, len(mmadd.callArgs))
	copy(argCopy, mmadd.callArgs)

	mmadd.mutex.RUnlock()

	return argCopy
}

// MinimockaddDone returns true if the count of the add invocations corresponds
// the number of defined expectations
func (m *RepositoryMock) MinimockaddDone() bool {
	if m.addMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.addMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.addMock.invocationsDone()
}

// MinimockaddInspect logs each unmet expectation
func (m *RepositoryMock) MinimockaddInspect() {
	for _, e := range m.addMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepositoryMock.add at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afteraddCounter := mm_atomic.LoadUint64(&m.afteraddCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.addMock.defaultExpectation != nil && afteraddCounter < 1 {
		if m.addMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RepositoryMock.add at\n%s", m.addMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RepositoryMock.add at\n%s with params: %#v", m.addMock.defaultExpectation.expectationOrigins.origin, *m.addMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcadd != nil && afteraddCounter < 1 {
		m.t.Errorf("Expected call to RepositoryMock.add at\n%s", m.funcaddOrigin)
	}

	if !m.addMock.invocationsDone() && afteraddCounter > 0 {
		m.t.Errorf("Expected %d calls to RepositoryMock.add at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.addMock.expectedInvocations), m.addMock.expectedInvocationsOrigin, afteraddCounter)
	}
}

type mRepositoryMockclear struct {
	optional           bool
	mock               *RepositoryMock
	defaultExpectation *RepositoryMockclearExpectation
	expectations       []*RepositoryMockclearExpectation

	callArgs []*RepositoryMockclearParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RepositoryMockclearExpectation specifies expectation struct of the RepositoryInterface.clear
type RepositoryMockclearExpectation struct {
	mock               *RepositoryMock
	params             *RepositoryMockclearParams
	paramPtrs          *RepositoryMockclearParamPtrs
	expectationOrigins RepositoryMockclearExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// RepositoryMockclearParams contains parameters of the RepositoryInterface.clear
type RepositoryMockclearParams struct {
	userID int64
}

// RepositoryMockclearParamPtrs contains pointers to parameters of the RepositoryInterface.clear
type RepositoryMockclearParamPtrs struct {
	userID *int64
}

// RepositoryMockclearOrigins contains origins of expectations of the RepositoryInterface.clear
type RepositoryMockclearExpectationOrigins struct {
	origin       string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmclear *mRepositoryMockclear) Optional() *mRepositoryMockclear {
	mmclear.optional = true
	return mmclear
}

// Expect sets up expected params for RepositoryInterface.clear
func (mmclear *mRepositoryMockclear) Expect(userID int64) *mRepositoryMockclear {
	if mmclear.mock.funcclear != nil {
		mmclear.mock.t.Fatalf("RepositoryMock.clear mock is already set by Set")
	}

	if mmclear.defaultExpectation == nil {
		mmclear.defaultExpectation = &RepositoryMockclearExpectation{}
	}

	if mmclear.defaultExpectation.paramPtrs != nil {
		mmclear.mock.t.Fatalf("RepositoryMock.clear mock is already set by ExpectParams functions")
	}

	mmclear.defaultExpectation.params = &RepositoryMockclearParams{userID}
	mmclear.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmclear.expectations {
		if minimock.Equal(e.params, mmclear.defaultExpectation.params) {
			mmclear.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmclear.defaultExpectation.params)
		}
	}

	return mmclear
}

// ExpectUserIDParam1 sets up expected param userID for RepositoryInterface.clear
func (mmclear *mRepositoryMockclear) ExpectUserIDParam1(userID int64) *mRepositoryMockclear {
	if mmclear.mock.funcclear != nil {
		mmclear.mock.t.Fatalf("RepositoryMock.clear mock is already set by Set")
	}

	if mmclear.defaultExpectation == nil {
		mmclear.defaultExpectation = &RepositoryMockclearExpectation{}
	}

	if mmclear.defaultExpectation.params != nil {
		mmclear.mock.t.Fatalf("RepositoryMock.clear mock is already set by Expect")
	}

	if mmclear.defaultExpectation.paramPtrs == nil {
		mmclear.defaultExpectation.paramPtrs = &RepositoryMockclearParamPtrs{}
	}
	mmclear.defaultExpectation.paramPtrs.userID = &userID
	mmclear.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmclear
}

// Inspect accepts an inspector function that has same arguments as the RepositoryInterface.clear
func (mmclear *mRepositoryMockclear) Inspect(f func(userID int64)) *mRepositoryMockclear {
	if mmclear.mock.inspectFuncclear != nil {
		mmclear.mock.t.Fatalf("Inspect function is already set for RepositoryMock.clear")
	}

	mmclear.mock.inspectFuncclear = f

	return mmclear
}

// Return sets up results that will be returned by RepositoryInterface.clear
func (mmclear *mRepositoryMockclear) Return() *RepositoryMock {
	if mmclear.mock.funcclear != nil {
		mmclear.mock.t.Fatalf("RepositoryMock.clear mock is already set by Set")
	}

	if mmclear.defaultExpectation == nil {
		mmclear.defaultExpectation = &RepositoryMockclearExpectation{mock: mmclear.mock}
	}

	mmclear.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmclear.mock
}

// Set uses given function f to mock the RepositoryInterface.clear method
func (mmclear *mRepositoryMockclear) Set(f func(userID int64)) *RepositoryMock {
	if mmclear.defaultExpectation != nil {
		mmclear.mock.t.Fatalf("Default expectation is already set for the RepositoryInterface.clear method")
	}

	if len(mmclear.expectations) > 0 {
		mmclear.mock.t.Fatalf("Some expectations are already set for the RepositoryInterface.clear method")
	}

	mmclear.mock.funcclear = f
	mmclear.mock.funcclearOrigin = minimock.CallerInfo(1)
	return mmclear.mock
}

// When sets expectation for the RepositoryInterface.clear which will trigger the result defined by the following
// Then helper
func (mmclear *mRepositoryMockclear) When(userID int64) *RepositoryMockclearExpectation {
	if mmclear.mock.funcclear != nil {
		mmclear.mock.t.Fatalf("RepositoryMock.clear mock is already set by Set")
	}

	expectation := &RepositoryMockclearExpectation{
		mock:               mmclear.mock,
		params:             &RepositoryMockclearParams{userID},
		expectationOrigins: RepositoryMockclearExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmclear.expectations = append(mmclear.expectations, expectation)
	return expectation
}

// Then sets up RepositoryInterface.clear return parameters for the expectation previously defined by the When method

func (e *RepositoryMockclearExpectation) Then() *RepositoryMock {
	return e.mock
}

// Times sets number of times RepositoryInterface.clear should be invoked
func (mmclear *mRepositoryMockclear) Times(n uint64) *mRepositoryMockclear {
	if n == 0 {
		mmclear.mock.t.Fatalf("Times of RepositoryMock.clear mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmclear.expectedInvocations, n)
	mmclear.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmclear
}

func (mmclear *mRepositoryMockclear) invocationsDone() bool {
	if len(mmclear.expectations) == 0 && mmclear.defaultExpectation == nil && mmclear.mock.funcclear == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmclear.mock.afterclearCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmclear.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// clear implements RepositoryInterface
func (mmclear *RepositoryMock) clear(userID int64) {
	mm_atomic.AddUint64(&mmclear.beforeclearCounter, 1)
	defer mm_atomic.AddUint64(&mmclear.afterclearCounter, 1)

	mmclear.t.Helper()

	if mmclear.inspectFuncclear != nil {
		mmclear.inspectFuncclear(userID)
	}

	mm_params := RepositoryMockclearParams{userID}

	// Record call args
	mmclear.clearMock.mutex.Lock()
	mmclear.clearMock.callArgs = append(mmclear.clearMock.callArgs, &mm_params)
	mmclear.clearMock.mutex.Unlock()

	for _, e := range mmclear.clearMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmclear.clearMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmclear.clearMock.defaultExpectation.Counter, 1)
		mm_want := mmclear.clearMock.defaultExpectation.params
		mm_want_ptrs := mmclear.clearMock.defaultExpectation.paramPtrs

		mm_got := RepositoryMockclearParams{userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmclear.t.Errorf("RepositoryMock.clear got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmclear.clearMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmclear.t.Errorf("RepositoryMock.clear got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmclear.clearMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmclear.funcclear != nil {
		mmclear.funcclear(userID)
		return
	}
	mmclear.t.Fatalf("Unexpected call to RepositoryMock.clear. %v", userID)

}

// clearAfterCounter returns a count of finished RepositoryMock.clear invocations
func (mmclear *RepositoryMock) clearAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmclear.afterclearCounter)
}

// clearBeforeCounter returns a count of RepositoryMock.clear invocations
func (mmclear *RepositoryMock) clearBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmclear.beforeclearCounter)
}

// Calls returns a list of arguments used in each call to RepositoryMock.clear.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmclear *mRepositoryMockclear) Calls() []*RepositoryMockclearParams {
	mmclear.mutex.RLock()

	argCopy := make([]*RepositoryMockclearParams, len(mmclear.callArgs))
	copy(argCopy, mmclear.callArgs)

	mmclear.mutex.RUnlock()

	return argCopy
}

// MinimockclearDone returns true if the count of the clear invocations corresponds
// the number of defined expectations
func (m *RepositoryMock) MinimockclearDone() bool {
	if m.clearMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.clearMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.clearMock.invocationsDone()
}

// MinimockclearInspect logs each unmet expectation
func (m *RepositoryMock) MinimockclearInspect() {
	for _, e := range m.clearMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepositoryMock.clear at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterclearCounter := mm_atomic.LoadUint64(&m.afterclearCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.clearMock.defaultExpectation != nil && afterclearCounter < 1 {
		if m.clearMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RepositoryMock.clear at\n%s", m.clearMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RepositoryMock.clear at\n%s with params: %#v", m.clearMock.defaultExpectation.expectationOrigins.origin, *m.clearMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcclear != nil && afterclearCounter < 1 {
		m.t.Errorf("Expected call to RepositoryMock.clear at\n%s", m.funcclearOrigin)
	}

	if !m.clearMock.invocationsDone() && afterclearCounter > 0 {
		m.t.Errorf("Expected %d calls to RepositoryMock.clear at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.clearMock.expectedInvocations), m.clearMock.expectedInvocationsOrigin, afterclearCounter)
	}
}

type mRepositoryMockget struct {
	optional           bool
	mock               *RepositoryMock
	defaultExpectation *RepositoryMockgetExpectation
	expectations       []*RepositoryMockgetExpectation

	callArgs []*RepositoryMockgetParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RepositoryMockgetExpectation specifies expectation struct of the RepositoryInterface.get
type RepositoryMockgetExpectation struct {
	mock               *RepositoryMock
	params             *RepositoryMockgetParams
	paramPtrs          *RepositoryMockgetParamPtrs
	expectationOrigins RepositoryMockgetExpectationOrigins
	results            *RepositoryMockgetResults
	returnOrigin       string
	Counter            uint64
}

// RepositoryMockgetParams contains parameters of the RepositoryInterface.get
type RepositoryMockgetParams struct {
	userID int64
}

// RepositoryMockgetParamPtrs contains pointers to parameters of the RepositoryInterface.get
type RepositoryMockgetParamPtrs struct {
	userID *int64
}

// RepositoryMockgetResults contains results of the RepositoryInterface.get
type RepositoryMockgetResults struct {
	m1 map[int64]Item
}

// RepositoryMockgetOrigins contains origins of expectations of the RepositoryInterface.get
type RepositoryMockgetExpectationOrigins struct {
	origin       string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmget *mRepositoryMockget) Optional() *mRepositoryMockget {
	mmget.optional = true
	return mmget
}

// Expect sets up expected params for RepositoryInterface.get
func (mmget *mRepositoryMockget) Expect(userID int64) *mRepositoryMockget {
	if mmget.mock.funcget != nil {
		mmget.mock.t.Fatalf("RepositoryMock.get mock is already set by Set")
	}

	if mmget.defaultExpectation == nil {
		mmget.defaultExpectation = &RepositoryMockgetExpectation{}
	}

	if mmget.defaultExpectation.paramPtrs != nil {
		mmget.mock.t.Fatalf("RepositoryMock.get mock is already set by ExpectParams functions")
	}

	mmget.defaultExpectation.params = &RepositoryMockgetParams{userID}
	mmget.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmget.expectations {
		if minimock.Equal(e.params, mmget.defaultExpectation.params) {
			mmget.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmget.defaultExpectation.params)
		}
	}

	return mmget
}

// ExpectUserIDParam1 sets up expected param userID for RepositoryInterface.get
func (mmget *mRepositoryMockget) ExpectUserIDParam1(userID int64) *mRepositoryMockget {
	if mmget.mock.funcget != nil {
		mmget.mock.t.Fatalf("RepositoryMock.get mock is already set by Set")
	}

	if mmget.defaultExpectation == nil {
		mmget.defaultExpectation = &RepositoryMockgetExpectation{}
	}

	if mmget.defaultExpectation.params != nil {
		mmget.mock.t.Fatalf("RepositoryMock.get mock is already set by Expect")
	}

	if mmget.defaultExpectation.paramPtrs == nil {
		mmget.defaultExpectation.paramPtrs = &RepositoryMockgetParamPtrs{}
	}
	mmget.defaultExpectation.paramPtrs.userID = &userID
	mmget.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmget
}

// Inspect accepts an inspector function that has same arguments as the RepositoryInterface.get
func (mmget *mRepositoryMockget) Inspect(f func(userID int64)) *mRepositoryMockget {
	if mmget.mock.inspectFuncget != nil {
		mmget.mock.t.Fatalf("Inspect function is already set for RepositoryMock.get")
	}

	mmget.mock.inspectFuncget = f

	return mmget
}

// Return sets up results that will be returned by RepositoryInterface.get
func (mmget *mRepositoryMockget) Return(m1 map[int64]Item) *RepositoryMock {
	if mmget.mock.funcget != nil {
		mmget.mock.t.Fatalf("RepositoryMock.get mock is already set by Set")
	}

	if mmget.defaultExpectation == nil {
		mmget.defaultExpectation = &RepositoryMockgetExpectation{mock: mmget.mock}
	}
	mmget.defaultExpectation.results = &RepositoryMockgetResults{m1}
	mmget.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmget.mock
}

// Set uses given function f to mock the RepositoryInterface.get method
func (mmget *mRepositoryMockget) Set(f func(userID int64) (m1 map[int64]Item)) *RepositoryMock {
	if mmget.defaultExpectation != nil {
		mmget.mock.t.Fatalf("Default expectation is already set for the RepositoryInterface.get method")
	}

	if len(mmget.expectations) > 0 {
		mmget.mock.t.Fatalf("Some expectations are already set for the RepositoryInterface.get method")
	}

	mmget.mock.funcget = f
	mmget.mock.funcgetOrigin = minimock.CallerInfo(1)
	return mmget.mock
}

// When sets expectation for the RepositoryInterface.get which will trigger the result defined by the following
// Then helper
func (mmget *mRepositoryMockget) When(userID int64) *RepositoryMockgetExpectation {
	if mmget.mock.funcget != nil {
		mmget.mock.t.Fatalf("RepositoryMock.get mock is already set by Set")
	}

	expectation := &RepositoryMockgetExpectation{
		mock:               mmget.mock,
		params:             &RepositoryMockgetParams{userID},
		expectationOrigins: RepositoryMockgetExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmget.expectations = append(mmget.expectations, expectation)
	return expectation
}

// Then sets up RepositoryInterface.get return parameters for the expectation previously defined by the When method
func (e *RepositoryMockgetExpectation) Then(m1 map[int64]Item) *RepositoryMock {
	e.results = &RepositoryMockgetResults{m1}
	return e.mock
}

// Times sets number of times RepositoryInterface.get should be invoked
func (mmget *mRepositoryMockget) Times(n uint64) *mRepositoryMockget {
	if n == 0 {
		mmget.mock.t.Fatalf("Times of RepositoryMock.get mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmget.expectedInvocations, n)
	mmget.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmget
}

func (mmget *mRepositoryMockget) invocationsDone() bool {
	if len(mmget.expectations) == 0 && mmget.defaultExpectation == nil && mmget.mock.funcget == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmget.mock.aftergetCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmget.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// get implements RepositoryInterface
func (mmget *RepositoryMock) get(userID int64) (m1 map[int64]Item) {
	mm_atomic.AddUint64(&mmget.beforegetCounter, 1)
	defer mm_atomic.AddUint64(&mmget.aftergetCounter, 1)

	mmget.t.Helper()

	if mmget.inspectFuncget != nil {
		mmget.inspectFuncget(userID)
	}

	mm_params := RepositoryMockgetParams{userID}

	// Record call args
	mmget.getMock.mutex.Lock()
	mmget.getMock.callArgs = append(mmget.getMock.callArgs, &mm_params)
	mmget.getMock.mutex.Unlock()

	for _, e := range mmget.getMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.m1
		}
	}

	if mmget.getMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmget.getMock.defaultExpectation.Counter, 1)
		mm_want := mmget.getMock.defaultExpectation.params
		mm_want_ptrs := mmget.getMock.defaultExpectation.paramPtrs

		mm_got := RepositoryMockgetParams{userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmget.t.Errorf("RepositoryMock.get got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmget.getMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmget.t.Errorf("RepositoryMock.get got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmget.getMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmget.getMock.defaultExpectation.results
		if mm_results == nil {
			mmget.t.Fatal("No results are set for the RepositoryMock.get")
		}
		return (*mm_results).m1
	}
	if mmget.funcget != nil {
		return mmget.funcget(userID)
	}
	mmget.t.Fatalf("Unexpected call to RepositoryMock.get. %v", userID)
	return
}

// getAfterCounter returns a count of finished RepositoryMock.get invocations
func (mmget *RepositoryMock) getAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmget.aftergetCounter)
}

// getBeforeCounter returns a count of RepositoryMock.get invocations
func (mmget *RepositoryMock) getBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmget.beforegetCounter)
}

// Calls returns a list of arguments used in each call to RepositoryMock.get.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmget *mRepositoryMockget) Calls() []*RepositoryMockgetParams {
	mmget.mutex.RLock()

	argCopy := make([]*RepositoryMockgetParams, len(mmget.callArgs))
	copy(argCopy, mmget.callArgs)

	mmget.mutex.RUnlock()

	return argCopy
}

// MinimockgetDone returns true if the count of the get invocations corresponds
// the number of defined expectations
func (m *RepositoryMock) MinimockgetDone() bool {
	if m.getMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.getMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.getMock.invocationsDone()
}

// MinimockgetInspect logs each unmet expectation
func (m *RepositoryMock) MinimockgetInspect() {
	for _, e := range m.getMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepositoryMock.get at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	aftergetCounter := mm_atomic.LoadUint64(&m.aftergetCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.getMock.defaultExpectation != nil && aftergetCounter < 1 {
		if m.getMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RepositoryMock.get at\n%s", m.getMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RepositoryMock.get at\n%s with params: %#v", m.getMock.defaultExpectation.expectationOrigins.origin, *m.getMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcget != nil && aftergetCounter < 1 {
		m.t.Errorf("Expected call to RepositoryMock.get at\n%s", m.funcgetOrigin)
	}

	if !m.getMock.invocationsDone() && aftergetCounter > 0 {
		m.t.Errorf("Expected %d calls to RepositoryMock.get at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.getMock.expectedInvocations), m.getMock.expectedInvocationsOrigin, aftergetCounter)
	}
}

type mRepositoryMockremove struct {
	optional           bool
	mock               *RepositoryMock
	defaultExpectation *RepositoryMockremoveExpectation
	expectations       []*RepositoryMockremoveExpectation

	callArgs []*RepositoryMockremoveParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RepositoryMockremoveExpectation specifies expectation struct of the RepositoryInterface.remove
type RepositoryMockremoveExpectation struct {
	mock               *RepositoryMock
	params             *RepositoryMockremoveParams
	paramPtrs          *RepositoryMockremoveParamPtrs
	expectationOrigins RepositoryMockremoveExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// RepositoryMockremoveParams contains parameters of the RepositoryInterface.remove
type RepositoryMockremoveParams struct {
	userID int64
	sku    int64
}

// RepositoryMockremoveParamPtrs contains pointers to parameters of the RepositoryInterface.remove
type RepositoryMockremoveParamPtrs struct {
	userID *int64
	sku    *int64
}

// RepositoryMockremoveOrigins contains origins of expectations of the RepositoryInterface.remove
type RepositoryMockremoveExpectationOrigins struct {
	origin       string
	originUserID string
	originSku    string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmremove *mRepositoryMockremove) Optional() *mRepositoryMockremove {
	mmremove.optional = true
	return mmremove
}

// Expect sets up expected params for RepositoryInterface.remove
func (mmremove *mRepositoryMockremove) Expect(userID int64, sku int64) *mRepositoryMockremove {
	if mmremove.mock.funcremove != nil {
		mmremove.mock.t.Fatalf("RepositoryMock.remove mock is already set by Set")
	}

	if mmremove.defaultExpectation == nil {
		mmremove.defaultExpectation = &RepositoryMockremoveExpectation{}
	}

	if mmremove.defaultExpectation.paramPtrs != nil {
		mmremove.mock.t.Fatalf("RepositoryMock.remove mock is already set by ExpectParams functions")
	}

	mmremove.defaultExpectation.params = &RepositoryMockremoveParams{userID, sku}
	mmremove.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmremove.expectations {
		if minimock.Equal(e.params, mmremove.defaultExpectation.params) {
			mmremove.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmremove.defaultExpectation.params)
		}
	}

	return mmremove
}

// ExpectUserIDParam1 sets up expected param userID for RepositoryInterface.remove
func (mmremove *mRepositoryMockremove) ExpectUserIDParam1(userID int64) *mRepositoryMockremove {
	if mmremove.mock.funcremove != nil {
		mmremove.mock.t.Fatalf("RepositoryMock.remove mock is already set by Set")
	}

	if mmremove.defaultExpectation == nil {
		mmremove.defaultExpectation = &RepositoryMockremoveExpectation{}
	}

	if mmremove.defaultExpectation.params != nil {
		mmremove.mock.t.Fatalf("RepositoryMock.remove mock is already set by Expect")
	}

	if mmremove.defaultExpectation.paramPtrs == nil {
		mmremove.defaultExpectation.paramPtrs = &RepositoryMockremoveParamPtrs{}
	}
	mmremove.defaultExpectation.paramPtrs.userID = &userID
	mmremove.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmremove
}

// ExpectSkuParam2 sets up expected param sku for RepositoryInterface.remove
func (mmremove *mRepositoryMockremove) ExpectSkuParam2(sku int64) *mRepositoryMockremove {
	if mmremove.mock.funcremove != nil {
		mmremove.mock.t.Fatalf("RepositoryMock.remove mock is already set by Set")
	}

	if mmremove.defaultExpectation == nil {
		mmremove.defaultExpectation = &RepositoryMockremoveExpectation{}
	}

	if mmremove.defaultExpectation.params != nil {
		mmremove.mock.t.Fatalf("RepositoryMock.remove mock is already set by Expect")
	}

	if mmremove.defaultExpectation.paramPtrs == nil {
		mmremove.defaultExpectation.paramPtrs = &RepositoryMockremoveParamPtrs{}
	}
	mmremove.defaultExpectation.paramPtrs.sku = &sku
	mmremove.defaultExpectation.expectationOrigins.originSku = minimock.CallerInfo(1)

	return mmremove
}

// Inspect accepts an inspector function that has same arguments as the RepositoryInterface.remove
func (mmremove *mRepositoryMockremove) Inspect(f func(userID int64, sku int64)) *mRepositoryMockremove {
	if mmremove.mock.inspectFuncremove != nil {
		mmremove.mock.t.Fatalf("Inspect function is already set for RepositoryMock.remove")
	}

	mmremove.mock.inspectFuncremove = f

	return mmremove
}

// Return sets up results that will be returned by RepositoryInterface.remove
func (mmremove *mRepositoryMockremove) Return() *RepositoryMock {
	if mmremove.mock.funcremove != nil {
		mmremove.mock.t.Fatalf("RepositoryMock.remove mock is already set by Set")
	}

	if mmremove.defaultExpectation == nil {
		mmremove.defaultExpectation = &RepositoryMockremoveExpectation{mock: mmremove.mock}
	}

	mmremove.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmremove.mock
}

// Set uses given function f to mock the RepositoryInterface.remove method
func (mmremove *mRepositoryMockremove) Set(f func(userID int64, sku int64)) *RepositoryMock {
	if mmremove.defaultExpectation != nil {
		mmremove.mock.t.Fatalf("Default expectation is already set for the RepositoryInterface.remove method")
	}

	if len(mmremove.expectations) > 0 {
		mmremove.mock.t.Fatalf("Some expectations are already set for the RepositoryInterface.remove method")
	}

	mmremove.mock.funcremove = f
	mmremove.mock.funcremoveOrigin = minimock.CallerInfo(1)
	return mmremove.mock
}

// When sets expectation for the RepositoryInterface.remove which will trigger the result defined by the following
// Then helper
func (mmremove *mRepositoryMockremove) When(userID int64, sku int64) *RepositoryMockremoveExpectation {
	if mmremove.mock.funcremove != nil {
		mmremove.mock.t.Fatalf("RepositoryMock.remove mock is already set by Set")
	}

	expectation := &RepositoryMockremoveExpectation{
		mock:               mmremove.mock,
		params:             &RepositoryMockremoveParams{userID, sku},
		expectationOrigins: RepositoryMockremoveExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmremove.expectations = append(mmremove.expectations, expectation)
	return expectation
}

// Then sets up RepositoryInterface.remove return parameters for the expectation previously defined by the When method

func (e *RepositoryMockremoveExpectation) Then() *RepositoryMock {
	return e.mock
}

// Times sets number of times RepositoryInterface.remove should be invoked
func (mmremove *mRepositoryMockremove) Times(n uint64) *mRepositoryMockremove {
	if n == 0 {
		mmremove.mock.t.Fatalf("Times of RepositoryMock.remove mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmremove.expectedInvocations, n)
	mmremove.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmremove
}

func (mmremove *mRepositoryMockremove) invocationsDone() bool {
	if len(mmremove.expectations) == 0 && mmremove.defaultExpectation == nil && mmremove.mock.funcremove == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmremove.mock.afterremoveCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmremove.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// remove implements RepositoryInterface
func (mmremove *RepositoryMock) remove(userID int64, sku int64) {
	mm_atomic.AddUint64(&mmremove.beforeremoveCounter, 1)
	defer mm_atomic.AddUint64(&mmremove.afterremoveCounter, 1)

	mmremove.t.Helper()

	if mmremove.inspectFuncremove != nil {
		mmremove.inspectFuncremove(userID, sku)
	}

	mm_params := RepositoryMockremoveParams{userID, sku}

	// Record call args
	mmremove.removeMock.mutex.Lock()
	mmremove.removeMock.callArgs = append(mmremove.removeMock.callArgs, &mm_params)
	mmremove.removeMock.mutex.Unlock()

	for _, e := range mmremove.removeMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmremove.removeMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmremove.removeMock.defaultExpectation.Counter, 1)
		mm_want := mmremove.removeMock.defaultExpectation.params
		mm_want_ptrs := mmremove.removeMock.defaultExpectation.paramPtrs

		mm_got := RepositoryMockremoveParams{userID, sku}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmremove.t.Errorf("RepositoryMock.remove got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmremove.removeMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.sku != nil && !minimock.Equal(*mm_want_ptrs.sku, mm_got.sku) {
				mmremove.t.Errorf("RepositoryMock.remove got unexpected parameter sku, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmremove.removeMock.defaultExpectation.expectationOrigins.originSku, *mm_want_ptrs.sku, mm_got.sku, minimock.Diff(*mm_want_ptrs.sku, mm_got.sku))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmremove.t.Errorf("RepositoryMock.remove got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmremove.removeMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmremove.funcremove != nil {
		mmremove.funcremove(userID, sku)
		return
	}
	mmremove.t.Fatalf("Unexpected call to RepositoryMock.remove. %v %v", userID, sku)

}

// removeAfterCounter returns a count of finished RepositoryMock.remove invocations
func (mmremove *RepositoryMock) removeAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmremove.afterremoveCounter)
}

// removeBeforeCounter returns a count of RepositoryMock.remove invocations
func (mmremove *RepositoryMock) removeBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmremove.beforeremoveCounter)
}

// Calls returns a list of arguments used in each call to RepositoryMock.remove.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmremove *mRepositoryMockremove) Calls() []*RepositoryMockremoveParams {
	mmremove.mutex.RLock()

	argCopy := make([]*RepositoryMockremoveParams, len(mmremove.callArgs))
	copy(argCopy, mmremove.callArgs)

	mmremove.mutex.RUnlock()

	return argCopy
}

// MinimockremoveDone returns true if the count of the remove invocations corresponds
// the number of defined expectations
func (m *RepositoryMock) MinimockremoveDone() bool {
	if m.removeMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.removeMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.removeMock.invocationsDone()
}

// MinimockremoveInspect logs each unmet expectation
func (m *RepositoryMock) MinimockremoveInspect() {
	for _, e := range m.removeMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepositoryMock.remove at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterremoveCounter := mm_atomic.LoadUint64(&m.afterremoveCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.removeMock.defaultExpectation != nil && afterremoveCounter < 1 {
		if m.removeMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RepositoryMock.remove at\n%s", m.removeMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RepositoryMock.remove at\n%s with params: %#v", m.removeMock.defaultExpectation.expectationOrigins.origin, *m.removeMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcremove != nil && afterremoveCounter < 1 {
		m.t.Errorf("Expected call to RepositoryMock.remove at\n%s", m.funcremoveOrigin)
	}

	if !m.removeMock.invocationsDone() && afterremoveCounter > 0 {
		m.t.Errorf("Expected %d calls to RepositoryMock.remove at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.removeMock.expectedInvocations), m.removeMock.expectedInvocationsOrigin, afterremoveCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockaddInspect()

			m.MinimockclearInspect()

			m.MinimockgetInspect()

			m.MinimockremoveInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockaddDone() &&
		m.MinimockclearDone() &&
		m.MinimockgetDone() &&
		m.MinimockremoveDone()
}
